#!/bin/bash
set -e

DB_NAME1="jiradb"
DB_NAME2="confluencedb"
DB_NAME3="crowddb"

DB_USER1="jira"
DB_USER2="confluence"
DB_USER3="crowd"

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database: ${DB_NAME1}"

$POSTGRES <<EOSQL
CREATE DATABASE ${DB_NAME1} WITH ENCODING 'UNICODE' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME1} TO ${DB_USER1};
EOSQL

echo "Creating database: ${DB_NAME2}"

$POSTGRES <<EOSQL
CREATE DATABASE ${DB_NAME2} WITH ENCODING 'UNICODE' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME2} TO ${DB_USER2};
EOSQL

echo "Creating database: ${DB_NAME3}"

$POSTGRES <<EOSQL
CREATE DATABASE ${DB_NAME3} WITH ENCODING 'UNICODE' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME3} TO ${DB_USER3};
EOSQL

